// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArrD-F_TPtBHRF6J7UJuFSzGYcEMTGVm4',
    appId: '1:729077655466:web:7dad76c78fde33bbcd6dd3',
    messagingSenderId: '729077655466',
    projectId: 'skygnosis-8e221',
    authDomain: 'skygnosis-8e221.firebaseapp.com',
    storageBucket: 'skygnosis-8e221.firebasestorage.app',
    measurementId: 'G-XTKE8W33X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAET-nyq08FP2uILFy5sUm7yJaOO_LxUps',
    appId: '1:729077655466:android:d15cad448a68bf40cd6dd3',
    messagingSenderId: '729077655466',
    projectId: 'skygnosis-8e221',
    storageBucket: 'skygnosis-8e221.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArrD-F_TPtBHRF6J7UJuFSzGYcEMTGVm4',
    appId: '1:729077655466:web:58ad7d97f3847b0dcd6dd3',
    messagingSenderId: '729077655466',
    projectId: 'skygnosis-8e221',
    authDomain: 'skygnosis-8e221.firebaseapp.com',
    storageBucket: 'skygnosis-8e221.firebasestorage.app',
    measurementId: 'G-4BVBVHMEN7',
  );
}
